name: Deploy Fixed Rental App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          apps/web/package-lock.json
          packages/api/package-lock.json
          packages/ui/package-lock.json
    
    - name: Install dependencies
      run: |
        npm ci
        cd apps/web && npm ci
        cd ../../packages/api && npm ci
        cd ../ui && npm ci
    
    - name: Build packages
      run: |
        cd packages/api && npm run build
        cd ../ui && npm run build
    
    - name: Build web app
      run: |
        cd apps/web && npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/web/out
