name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

# Optional but recommended: avoid overlapping runs for Pages
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:                      # <-- the job id MUST be exactly "deploy"
    runs-on: ubuntu-latest
    environment:              # <-- required by actions/deploy-pages@v4
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: apps/web
        run: npm ci

      - name: Build static
        working-directory: apps/web
        run: npm run build:static

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy build output to docs
        run: cp -r apps/web/out/* docs/

      - name: VERIFY docs contents
        run: |
          echo "Listing docs directory:"
          ls -lah docs || true
          test -f docs/index.html || (echo "ERROR: docs/index.html missing"; exit 1)

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
