name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd apps/web
          npm install
          
      - name: Build Next.js app
        run: |
          cd apps/web
          npm run build:static
          echo "Build completed. Files in out/:"
          ls -la out/
          echo "Checking for index.html:"
          find out/ -name "index.html" -type f
          echo "Checking for 404.html:"
          find out/ -name "404.html" -type f
          
      - name: Copy root index.html
        run: |
          cd apps/web
          cp public/index.html out/
          echo "Root index.html copied to out/"
          
      - name: Verify upload contents
        run: |
          cd apps/web
          echo "Final contents of out/ directory:"
          ls -la out/
          echo "Checking for critical files:"
          ls -la out/index.html
          ls -la out/404.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
