name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd apps/web
          npm install
          
      - name: Build Next.js app
        working-directory: apps/web
        run: |
          npm run build:static
          echo "Build completed. Files in out/:"
          ls -la out/
          
      - name: Copy root index.html to build output
        working-directory: apps/web
        run: |
          cp public/index.html out/
          echo "Root index.html copied to build output"
          
      - name: Verify build output structure
        working-directory: apps/web
        run: |
          echo "Final build output structure:"
          ls -la out/
          echo "Root index.html exists:"
          ls -la out/index.html
          echo "404.html exists:"
          ls -la out/404.html
          echo "Rental_App directory exists:"
          ls -la out/Rental_App/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
