name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Build packages first
        run: npm run build:packages

      - name: Build static
        working-directory: apps/web
        run: npm run build:static

      - name: SPA fallback and deploy preparation
        run: |
          # SPA fallback for deep links
          cp apps/web/out/index.html apps/web/out/404.html
          
          # Guard: fail if any relative 'Rental_App/_next' slipped into HTML
          if grep -R --include="*.html" -n 'href="Rental_App/_next' apps/web/out || \
             grep -R --include="*.html" -n 'src="Rental_App/_next' apps/web/out; then
            echo "ERROR: Found relative Rental_App/_next paths (would cause /Rental_App/Rental_App)."
            exit 1
          fi
          
          # Publish exported site to docs/ (no extra subfolder)
          rm -rf docs
          mkdir -p docs
          cp -r apps/web/out/* docs/

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
