name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: Rental_App
        run: npm install

      - name: Build packages first
        working-directory: Rental_App
        run: npm run build:packages

      - name: Build static
        working-directory: Rental_App/apps/web
        run: npm run build:static

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy build output to docs
        run: cp -rv Rental_App/apps/web/out/* docs/

      - name: Fix asset paths for GitHub Pages
        run: |
          cd docs
          echo "=== FIXING ASSET PATHS ==="
          # Fix _next asset paths to include /Rental_App prefix
          # Use more precise patterns that will actually match
          find . -name "*.html" -exec sed -i 's|href="/_next/|href="/Rental_App/_next/|g' {} \;
          find . -name "*.html" -exec sed -i 's|src="/_next/|src="/Rental_App/_next/|g' {} \;
          find . -name "*.js" -exec sed -i 's|"/_next/|"/Rental_App/_next/|g' {} \;
          find . -name "*.js" -exec sed -i 's|/_next/|/Rental_App/_next/|g' {} \;
          find . -name "*.css" -exec sed -i 's|url("/_next/|url("/Rental_App/_next/|g' {} \;
          find . -name "*.css" -exec sed -i 's|url(/_next/|url(/Rental_App/_next/|g' {} \;
          echo "Asset paths fixed"

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
