name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: Rental_App
        run: npm install

      - name: Build packages first
        working-directory: Rental_App
        run: npm run build:packages

      - name: Build static
        working-directory: Rental_App/apps/web
        run: npm run build:static

      - name: DEBUG: Check build output
        run: echo "=== BUILD OUTPUT DEBUG ===" && echo "Current directory: $(pwd)" && echo "Listing apps/web/out:" && ls -la Rental_App/apps/web/out || echo "out directory not found" && echo "Checking for index.html:" && find Rental_App/apps/web/out -name "index.html" -type f || echo "No index.html found"

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy build output to docs
        run: |
          echo "=== COPY DEBUG ==="
          echo "Copying from Rental_App/apps/web/out to docs"
          cp -rv Rental_App/apps/web/out/* docs/ || echo "Copy failed"
          echo "Listing docs after copy:"
          ls -la docs || echo "docs directory empty"

      - name: Fix asset paths for GitHub Pages
        run: |
          echo "=== FIXING ASSET PATHS ==="
          cd docs
          find . -name "*.html" -exec sed -i 's|/_next/|/Rental_App/_next/|g' {} \;
          find . -name "*.js" -exec sed -i 's|/_next/|/Rental_App/_next/|g' {} \;
          find . -name "*.css" -exec sed -i 's|/_next/|/Rental_App/_next/|g' {} \;
          echo "Asset paths fixed"

      - name: VERIFY docs contents
        run: |
          echo "=== VERIFICATION ==="
          echo "Listing docs directory:"
          ls -la docs || echo "docs directory not found"
          echo "Checking for index.html in docs:"
          test -f docs/index.html && echo "SUCCESS: docs/index.html exists" || (echo "ERROR: docs/index.html missing"; exit 1)
          echo "Checking if asset paths were fixed:"
          grep -r "_next" docs/ | head -5 || echo "No _next references found"

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
