name: Test - GitHub Actions Working

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test - Confirm Actions Working
        run: |
          echo "✅ GitHub Actions is working!"
          echo "✅ Repository: ${{ github.repository }}"
          echo "✅ Branch: ${{ github.ref }}"
          echo "✅ Commit: ${{ github.sha }}"
          echo "✅ Current time: $(date)"
